In [8]:
import numpy
a = numpy.arange(12)  # inspect a numpy.ndarray with int 0 to 11.
print(a)
print(type(a))
print(a.shape)  # inspect dimensions of arr: it's 1-d, 12 elem arr
a.shape = 3, 4
print(a)

print(a[2])
print(a[2, 1])  # second inner array and second item in that array
print(a[:, 1])  # create a new arr by transposing (swapping cols with rows)
print(a.transpose())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
